version: '3.8'
services:
  api-central:
    build: .
    container_name: api-central
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - sqlserver
    networks:
      - mynet
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - mynet

networks:
  mynet:

volumes:
  mongo-data:
  sqlserver-data:
